### ISSUE TITLE
Linden Scripting Language doesn't seem to be working.

### ISSUE THREAD

**Issue by MarcusLlewellyn** [buildersbrewery/linden-scripting-language#1]
First, thank you for the effort put into all of these file for so many different editors. It must be a titanic effort!

Just wanted to note that the LSL support files for Visual Studio Code don't appear to be working. I've tried it with versions 0.7.0 and 0.8.0. I appreciate that this editor is a moving target that is actively under development. I'm confident that I've copied the vs.language.lsl folder into the correct lo the correct location for both versions.

**Comment by buildersbrewery** [comment]
Microsoft hasn't published an API, yet. That should be coming with one of the next versions.
The Visual Studio Code files of the current commit are random files adjusted for use with LSL that I've put together from various sources and languages.
If you want basic LSL support for VS Code, I believe copying the completions file and a copy of `sublimetext/LSL/syntaxes/LSL.hidden-tmLanguage` renamed to `*.tmLanguage` should do.
As of now it's just a bunch of files to get started as soon as there's some kind of API from Microsoft.

**Comment by MarcusLlewellyn** [comment]
Thanks for the prompt reply. As basic highlighting was all I'm really hoping for, I'll give your suggestion a shot, and close this issue.

**Comment by buildersbrewery** [comment]
- [x] add changes from:
  http://wiki.secondlife.com/wiki/Release_Notes/Second_Life_RC_LeTigre/15#15.09.14.305056

**Comment by buildersbrewery** [comment]
@MarcusLlewellyn

Do the latest changes work for you? Please reopen with comment if not.

**Comment by buildersbrewery** [comment]
or comment directly on 4f73668

**Comment by buildersbrewery** [comment]
btw changes are untested, it's late at night here but wanted to publish early and move fast.

**Comment by buildersbrewery** [comment]
@MarcusLlewellyn VS Code has left preview status and been released as beta. Extension support seems finalized, I'll be looking into updating the files next week as I'm busy this week.

**Comment by yaSebastian** [comment]
Are there any plans on creating an official VS Code extension, uploading it to the Visual Studio Marketplace? I might be interested in getting involved.

**Comment by buildersbrewery** [comment]
@yaSebastian

Currently no plans from my side. Should you be willing to do that, FYI some links below:

* #19 has pending updates listed in regards to the LSL grammar
* [digitalfiz/language-lsl](https://github.com/digitalfiz/language-lsl) has the *official* [Atom](https://atom.io) extension, in case that helps.
  * digitalfiz/language-lsl#17 has pending changes there in regards to [lslforge](https://github.com/elnewfie/lslforge) support

What are your plans? I'd accept a PR to fix #19 and add [lslforge](https://github.com/elnewfie/lslforge) support, should you want to start from there.
