### ISSUE TITLE
Autocompletion in Notepad++, hints/popup not always working

### ISSUE THREAD

**Issue by RayZopf** [buildersbrewery/linden-scripting-language#28]
### Issue Summary

use the Autocomplition feature (without FingerText enabled)

- popup hint works on `llListen` but not on `listen`
- works on `llSensor` but not on `sensor`

### Steps to Reproduce

1. type `llListen`
2. go on and add `(`
3. see the popup/hint explaining parameters

compared to

1. type `listen`
2. go on and add `(`
3. see nothing happening

### Technical details

bug is as follows:

```xml
    <KeyWord name="listen" func="yes">
        <Overload descr="Triggered by chat, use llListen to enable and filter.">
            <Param name="integer channel" />
            <Param name="string name" />
            <Param name="key id" />
            <Param name="string message" />
        </Overload>
    </KeyWord>
```

has no `retVal="XXX"`. However for functions I could spot `retVal="void"`, but even `retVal=""` makes it work again

```xml
    <KeyWord name="listen" func="yes">
        <Overload retVal="" descr="Triggered by chat, use llListen to enable and filter.">
            <Param name="integer channel" />
            <Param name="string name" />
            <Param name="key id" />
            <Param name="string message" />
        </Overload>
    </KeyWord>
```

* Editor: Notepadd++
* Version: 7.3.3
* Operating System: Win7 x64

**Comment by buildersbrewery** [comment]
Technically `listen` isn't a function, so it's wrong anyway. I'll review the docs for `Notepad++` and see if there's a better way now to do this.

**Comment by buildersbrewery** [comment]
* <http://docs.notepad-plus-plus.org/index.php/Auto_Completion>
* <http://docs.notepad-plus-plus.org/index.php/Configuration_Files>
* <http://docs.notepad-plus-plus.org/index.php/Editing_Configuration_Files>, see section `Autocompletion`

**Comment by RayZopf** [comment]
### according to the last document

> When a <KeyWord> tag is not auto-closing, it must have a second attribute, "func", set to "yes".

so this is correct
`<KeyWord name="listen" func="yes">`

>  Overload> has a "retVal" attribute, which you would set to the initial comment in the call tip. In C/C++, this traditionally would be the return type; "" is a permitted value.

so this will be ok - and fix the not appearing  _parameter hint (a.k.a. a "call tip"):_

` <Overload retVal="" descr="Triggered by chat, use llListen to enable and filter.">`

**Comment by RayZopf** [comment]
[reworked lsl.xml](https://gist.github.com/RayZopf/5732345b365b9580d69a26140041fbcf)

**Comment by buildersbrewery** [comment]
@RayZopf Thanks, I'm currently abroad on vacation. I'll get back to this when I get back at the end of this month.
