### ISSUE TITLE
Improve Notepad++ install manual

### ISSUE THREAD

**Issue by RayZopf** [buildersbrewery/linden-scripting-language#29]
### Issue Summary

Notepad++ makes use of two directory structures

- C:\Program Files (x86)\Notepad++ (using 32bit version, 'install dir')
- C:\Users\USERNAME\AppData\Roaming\Notepad++

some of the files should go to user account folders _(funtionList.xml, userDefineLang.xml)_
others need to be in install dir _(lsl.xml)_

### Steps to Reproduce

1. copy _lsl.xml_ into user folder structure
2. see that it does not work
3. delete file from user folder structure, add into install dir folders
4. see autocomplete working

compare to _funtionList.xml_
where the NP++ website says

>  It can be found in %APPDATA%\notepad++\ or in Notepad++ installed directory if you use zip package.

putting it into user account folder structure makes that feature work and is probably better than editing the _functionList.xml_ that is already present in install dirs

_userDefineLang.xml_ definitely should go into %APPDATA% structure

### Technical details

* Editor: NP++
* Version: 7.3.3
* Operating System: Win7 x64

**Comment by buildersbrewery** [comment]
The installation instructions are for the portable version. I'll add the paths for the installed version.
