### ISSUE TITLE
STATUS_CAST_SHADOWS

### ISSUE THREAD

**Issue by buildersbrewery** [buildersbrewery/linden-scripting-language#34]
Should be marked as `"deprecated"` according to SL wiki.

Compare:

* <http://wiki.secondlife.com/wiki/STATUS_CAST_SHADOWS>
* `PRIM_CAST_SHADOWS`

**Comment by buildersbrewery** [comment]
@Sei-Lisa FYI, this bug is also in `kwdb`.

---

@XenHat @makopo

**Comment by Sei-Lisa** [comment]
Thanks, fixed.
