### ISSUE TITLE
[WIP] Set up tests for Sublime Text 3 package

### ISSUE THREAD

**Issue by buildersbrewery** [buildersbrewery/linden-scripting-language#36]
Use:

* <https://github.com/randy3k/UnitTesting>
  * <https://github.com/gerardroche/sublime-color-scheme-unit>
    * related:
      * <https://github.com/gerardroche/UnitTesting/tree/develop>
      * randy3k/UnitTesting#59
* <https://github.com/randy3k/UnitTesting-example>

---

Prepare to run the following tests:

* syntax tests in [`./syntaxes/tests/`](https://github.com/buildersbrewery/linden-scripting-language/tree/master/sublimetext/LSL/syntaxes/tests/)
* color scheme tests in [`./tests/`](https://github.com/buildersbrewery/linden-scripting-language/tree/master/sublimetext/LSL/tests)

**Comment by Sei-Lisa** [comment]
Why should I care? I have never run sublime text nor do I plan to.

**Comment by buildersbrewery** [comment]
@XenHat Should be able to run SublimeLinter with lslint as well, looking into it now...

**Comment by XenHat** [comment]
What is going on here?

**Comment by XenHat** [comment]
uuuh, what's the big idea?

**Comment by XenHat** [comment]
Maybe I'm getting the wrong idea here, but this makes me want to stop collaborating.
You can contact me for less public-facing discussions and debates [in-world](https://my.secondlife.com/xenhat.liamano).

**Comment by buildersbrewery** [comment]
moved to <https://github.com/buildersbrewery/sublime-lsl>
