### ISSUE TITLE
Add new constants

### ISSUE THREAD

**Issue by buildersbrewery** [buildersbrewery/linden-scripting-language#4]
``` lsl
integer OBJECT_PRIM_COUNT = 30;
integer OBJECT_TOTAL_INVENTORY_COUNT = 31;
integer OBJECT_REZZER_KEY = 32;
```

**Comment by BlindWanderer** [comment]
https://wiki.secondlife.com/wiki/Release_Notes/Second_Life_Server/16

**Comment by buildersbrewery** [comment]
@BlindWanderer thanks for the Link, Strife. I haven't made some time to push an update yet, though. Will do it tonight, if possible.
