### ISSUE TITLE
Atom package name collision.

### ISSUE THREAD

**Issue by strawberryangel** [buildersbrewery/linden-scripting-language#40]
### Issue Summary

(I could query quickly submit a pull request, but I feel this is a Bulder's Brewery administrative decision that should be made first.)

The package name for the Atom plugin is `language-lsl` which conflicts with digitalfiz's LSL plugin. 

Package name collision prevents updates from within Atom. 

I'd recommend changing the package name to something different, perhaps like `language-lsl-bb` to distinguish the Bulder's Brewery version from the digitalfiz version. 

### Steps to Reproduce

1. Install the Bulder's Brewery LSL package. 

You'll see the update message continually because it's trying to reconcile the installed Bulder's Brewery package with the registered `language-lsl` package by digitalfiz. 

![fd90c61fa51f21f0608df4c0bb0d2954](https://user-images.githubusercontent.com/2577636/32814299-47aedba4-c963-11e7-93bd-9da2a1018ef4.png)

Also, the two plugins collide. If I install the digitalfiz LSL plugin, an then the Builder's Brewery plugin, the digitalfiz plugin thinks that there's an update for it (because of the naming collision). 

If I install the Builder's Brewery plugin first, the digitalfiz LSL plugin won't install. 

#### Reasoning

To address the rebuttal, "Why would anybody want to install both?" 

1. It would be nice to compare the two plugins. 
2. It would open the road to making the Builder Brewery's version available to everybody who searches for LSL in Atom's plugin manager. Right now only the digitalfiz version appears in the list.)
3. To be blunt, I see that reasoning as excusing broken behavior to avoid fixing it. 

![ecf742cd72e1cebf05dde5b325252a84](https://user-images.githubusercontent.com/2577636/32814640-02f7feb2-c965-11e7-9205-8a5d09fac1b8.png)
 

### Technical details

* Editor: Atom
* Version: 1.22.0 x64
* Operating System: Window 10

**Comment by strawberryangel** [comment]
With a rename, the two packages can coexist just fine (assuming only one is active *wink* ).

![3d3f82cab9a7f561604cce930c335ac7](https://user-images.githubusercontent.com/2577636/32814882-d633fb5a-c965-11e7-8aa4-4f3447dee974.png)

**Comment by buildersbrewery** [comment]
@strawberryangel I'm not excusing anything here. If you feel entitled to demand anything, please move along. The package [`digitalfiz/language-lsl`](https://github.com/digitalfiz/language-lsl) works fine as you said, but hasn't been updated in a while. If you look at the contributors page there, you'll see that I've contributed quite a lot of code to that third party package.

In case you have code to contribute here, please open a pull request. The code posted here is a **free service** to the community and a **lot of work**. I don't even use most editors, never have and never will.

On a more general note: Complaining is easy and cheap. Doing the work takes time and effort. Please keep that in mind.

**Comment by strawberryangel** [comment]
I'm sorry if my comments were taken entirely the wrong way. 

I made **no complaint**. I'm making no demands. **I said that I can submit a pull request very easily,** but thought that I shouldn't make this change without review.

**Comment by strawberryangel** [comment]
"(I could query quickly submit a pull request, but I feel this is a Bulder's Brewery administrative decision that should be made first.)" 

Since there was no objection to the change, I'll go ahead and make a pull request, perhaps tonight.
