### ISSUE TITLE
Error in userDefinedLang.xml

### ISSUE THREAD

**Issue by SundanceHaiku** [buildersbrewery/linden-scripting-language#41]
### Issue Summary

This causes an issue because ... It shows up in the xml file

### Steps to Reproduce

1. Open `userDefineLang.xml`
2. Look at line 33.
3. You'll see:

```xml
<Keywords name="Delimiters" id="24">00&quot; 01\ 02&quot; 03BUG: 03Bug: 03bug: 03FIXME: 03Fixme: 03fixme: 03TEST: 03Test: 03test: 03TODO: 03Todo: 03todo: 04 05((EOL)) 05((EOL)) 05((EOL)) 05((EOL)) 05((EOL)) 05((EOL)) 05((EOL)) 05((EOL)) 05((EOL)) 05((EOL)) 05((EOL)) 05((EOL)) 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23</Keywords>
```

This indicates some sort of error with xml file.  It's probably easily cleaned up by someone who knows what they are doing.  I tried working with it in Notepad++ using the language editor, but I created more problems than solve this one.  That may be because I'm not very familiar with how to work in Notepad++.   Hopefully, someone with more experience will take this on and clean things up.

### Technical details

* Editor: `Notepad++`
* Version:
* Operating System: `Windows`

**Comment by buildersbrewery** [comment]
Thanks for the report.

---

If you compare the code in the repo at the current state, you'll see that:

https://github.com/buildersbrewery/linden-scripting-language/blob/120b7ebd905a81df9dc9c2c32a40bc399a42112e/notepad%2B%2B/userDefineLang.xml#L33

the quotes `"` are escaped properly as `&quot;`. Make sure you have your quotes escaped as well, compare <https://en.wikipedia.org/wiki/XML#Escaping>.

**Comment by buildersbrewery** [comment]
Also, try setting `Notepad++` to `Edit >> EOL conversion >> Windows format` when editing that file.

**Comment by SundanceHaiku** [comment]
Thank you for taking the time to provide information on this.  I will follow up on your advice.  

By the way, thank you so much for making this available.  There is nothing better than the tools you provide here for working with LSL code.  It is obvious that you have spent many hours putting this together and your work is truly appreciated.

**Comment by buildersbrewery** [comment]
@SundanceHaiku closing now, please reopen if problems persist
