### ISSUE TITLE
add changes for EEP LSL

### ISSUE THREAD

**Issue by buildersbrewery** [buildersbrewery/linden-scripting-language#44]
* add new constants: SKY_ABSORPTION_CONFIG, SKY_AMBIENT, SKY_CLOUDS, SKY_DENSITY_PROFILE_COUNTS, SKY_DOME, SKY_GAMMA, SKY_GLOW, SKY_LIGHT, SKY_MIE_CONFIG, SKY_MOON, SKY_PLANET, SKY_RAYLEIGH_CONFIG, SKY_REFRACTION, SKY_STAR_BRIGHTNESS, SKY_SUN, SKY_TEXTURE_DEFAULTS, SKY_TRACKS, WATER_BLUR_MULTIPLIER, WATER_FOG, WATER_FRESNEL, WATER_NORMAL_SCALE, WATER_REFRACTION, WATER_TEXTURE_DEFAULTS, WATER_WAVE_DIRECTION
* add new functions: llGetDayLength, llGetDayOffset, llGetEnvironment, llGetMoonDirection, llGetMoonRotation, llGetRegionDayLength, llGetRegionDayOffset, llGetRegionMoonDirection, llGetRegionMoonRotation, llGetRegionSunDirection, llGetRegionSunRotation, llGetSunRotation

See also:

* <https://community.secondlife.com/forums/topic/429648-eep-lsl-scripting/>
* <https://community.secondlife.com/forums/topic/432351-lsl-eep-scripting-documentation/>

**Comment by buildersbrewery** [comment]
* integer llReplaceAgentEnvironment(key agent_id, float transition, string environment)
  * ENV_NOT_EXPERIENCE
  * ENV_NO_EXPERIENCE_PERMISSION
  * ENV_NO_ENVIRONMENT
  * ENV_INVALID_AGENT
  * ENV_NO_EXPERIENCE
* llSetAgentEnvironment(key agent_id, float transition, list params)

**Comment by Mace68** [comment]
I've added EEP and Animesh keywords (I hope I got them all) to the Notepad++ files and have sent pull requests for those. I updated the install instructions a little too since Notepad++ seems to have changed a couple of things.

I hope I did all of this right, I'm new to contributing via git.

**Comment by buildersbrewery** [comment]
@Mace68 I didn't receive any pull request. You can open them by clicking **create pull request** via:

* https://github.com/buildersbrewery/linden-scripting-language/compare/master...Mace68:Mace68-patch-1
* https://github.com/buildersbrewery/linden-scripting-language/compare/master...Mace68:Mace68-patch-2
* https://github.com/buildersbrewery/linden-scripting-language/compare/master...Mace68:Mace68-patch-3
