### ISSUE TITLE
[Suggestion] Include, or add a link to, the LSL syntax checker for the Nova editor (macOS)

### ISSUE THREAD

**Issue by GwynethLlewelyn** [buildersbrewery/linden-scripting-language#52]
Hi! This is neither a feature request, much less an issue, but I just wanted to tell you that you're most welcome to add to your list the [LSL syntax extension that I've been writing for the Nova code editor](https://github.com/GwynethLlewelyn/LSL.novaextension). Nova users can simply add it from the Nova Extension Library, searching for 'LSL'. 

Nova is a commercial product that only runs under macOS, so I expect its usage by SL scripters to be very small. Still, the extension is there for anyone who wants to use it; it's still not 100% functional — like everything else, it's a WiP — and I'm trying to get it up-to-date with the [KWDB](https://github.com/Sei-Lisa/kwdb) automatically (it's absurd _not_ to use Sei Lisa and Mako Nozaki's fantastic work!), so it might make more sense to add it as a Git submodule on your repository — or perhaps just a link from the README could suffice.

Thanks!

**Comment by buildersbrewery** [comment]
@GwynethLlewelyn you can use a github workflow action with a cron job

**Comment by GwynethLlewelyn** [comment]
Oh — thanks so much for the tip! I'm really a newbie in terms of GitHub workflows (and just use them essentially to validate my code, when applicable). Since there are new LSL instructions for the KVP store, I need to update my LSL syntax extension, and I'll experiment a bit with GitHub actions to see if I can figure out how to do it!
